return {
  {
    "mason-org/mason.nvim",
    cmd = "Mason",
    keys = { { "<leader>cm", "<cmd>Mason<cr>", desc = "Mason" } },
    build = ":MasonUpdate",
    opts_extend = { "ensure_installed" },
    opts = {
      registries = { "github:crashdummyy/mason-registry", "github:mason-org/mason-registry" },
      ensure_installed = {
        "stylua",
        "shfmt",
        "lua-language-server",
        "xmlformatter",
        "csharpier",
        "html-lsp",
        "css-lsp",
        "vtsls",
        "biome",
        "json-lsp",
        "roslyn",
        "netcoredbg",
        "black",
        "clangd",
        "clang-format",
        "codelldb",
        "powershell-editor-services",
      },
    },
  },
}
